jaffle_shop: # this needs to match the profile in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /Users/agustinadisiot/Downloads/dbt-learn-360618-4873c22a41da.json # replace this with the full path to your keyfile
      project: dbt-learn-360618 # Replace this with your project id
      dataset: dbt_agustinadisiot # Replace this with dbt_your_name, e.g. dbt_bilbo
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive